### ISSUE TITLE
joins but doesnt play any sounds

### ISSUE THREAD

**Issue by Toastyisburning** [aaronr5tv/BigBenBot#2]
ive been trying to replicate the issue cause sometimes it shows an error but i cannot seem it get it to show up

**Comment by aaronr5tv** [comment]
Most likely because you don't have ffmpeg. Discord.js requires ffmpeg to be installed to play audio. ffmpeg is essentially just programs used for handling multimedia data. If you haven't pulled down the latest version of the repo try that as I added `ffmpeg-static` to the dependencies and run `npm install` again or you could just navigate to your project folder and run `npm i -S ffmpeg-static` to install the dependency. Also alternatively you could go to the ffmpeg website and download and install it on your system.
